import React from 'react';
import { useLocation } from 'react-router-dom';
import '../styles/index.css'; // Import your CSS styles
import DynamicForm from './DynamicForm';

const ServiceInfo = () => {
    const location = useLocation();
    const { serviceName } = location.state || {};

    
  const services = [
    {id: 1, name: 'Ländrygg', price: '3 900kr', title:'Magnetröntgen Ländrygg', detail: 'Ryggvärk är ett väldigt vanligt symtom är den tredje vanligaste diagnosen vid långa sjukskrivningar. Långvarig ryggsmärta kan leda till stora begränsningar i vardagen och ett stort psykiskt lidande. Undersökning med magnetkamera möjliggör snabb diagnos av eventuella diskbråck och ryggmärgssjukdomar. Tillsammans med din symtombild möjliggör det en korrekt diagnos vilket ger optimala förutsättningar för rätt behandling och rehabilitering. Undersökningen är ofarlig, smärtfri och du utsätts inte för farlig joniserande strålning. Alla bilder granskas av erfarna specialistläkare inom radiologi. ', restrictions: 'Du kan inte undersökas i magnetkamera om du har metallsplitter i någon del av kroppen, pacemaker, insulinpump eller annan elektronisk utrustning inopererad. Däremot går det att genomföra undersökningen om du har icke magnetisk metall, som till exempel höft- eller knäledsprotes eller tandfyllning.' },
    {id: 2, name: 'Halsrygg', price: '3 900kr', title:'Magnetröntgen Halsrygg', detail: 'Ryggvärk är ett väldigt vanligt symtom är den tredje vanligaste diagnosen vid långa sjukskrivningar. Långvarig ryggsmärta kan leda till stora begränsningar i vardagen och ett stort psykiskt lidande. Undersökning med magnetkamera möjliggör snabb diagnos av eventuella diskbråck och ryggmärgssjukdomar. Tillsammans med din symtombild möjliggör det en korrekt diagnos vilket ger optimala förutsättningar för rätt behandling och rehabilitering. Undersökningen är ofarlig, smärtfri och du utsätts inte för farlig joniserande strålning. Alla bilder granskas av erfarna specialistläkare inom radiologi. ' },
    {id: 3, name: 'Axel', price: '4 100kr', title:'Magnetröntgen Axel', detail: 'Smärta från axelleden är en vanlig åkomma och kan orsaka stora inskränkningar i din vardag. Har du ont i axeln kan det bero på inflammation, artros eller skada på senor och muskler i rotatorkuffen. En av de vanligaste orsakerna till smärta i axelleden är impingement. Det innebär att strukturer i axeln kommer i kläm och det orsakar smärta vid rörelse. Andra vanligt förekommande tillstånd är frusen skuldra (frozen shoulder) och kalkaxel. En magnetkameraundersökning av axeln kan bidra med en snabb diagnos och möjlighet till rätt behandling och rehabilitering.' },
    {id: 4, name: 'Bäcken/höftleder', price: '3 900kr', title:'Magnetröntgen Bäcken/höfleder', detail: 'En magnetkameraundersökning av bäcken och höftleder kan påvisa inflammation i muskelfästen och senskidor vilket kan vara av vikt vid exempelvis oklara smärttillstånd i bäcken- och höftområdet.  Man kan exempelvis påvisa slemsäcksinflammation (bursit) eller artros. ' },
    {id: 5, name: 'Knä', price: '3 900kr', title:'Magnetröntgen Knä', detail: 'Magnetkameraundersökning av knät är en bra undersökning för att upptäcka skada på t.ex. korsband, ledband och menisk. En korsbandsskada kan uppstå efter förhållandevis lindrigt trauma och kan leda till smärta, svullnad samt instabilitet i knäleden. En undersökning med magnetkamera kan tidigt upptäcka en korsbandsskada och möjliggöra rätt behandling och rehabilitering. Andra sjukdomstillstånd i knäet som är svåra att diagnostisera utan en MR är meniskskada, ledbandsskada samt patellaskada.' },
    {id: 6, name: 'Helkropp', price: '16 200kr', title:'Magnetröntgen Helkropp', detail: 'En magnetkameraundersökning helkropp ger en god överblick över kroppens organ. Det är en avancerad undersökning som visualiserar och kartlägger dina organ så att eventuella sjukdomar såsom cancer och hjärt- och kärlsjukdom kan upptäckas tidigt vilket optimerar förutsättningar för behandling. Allvarliga sjukdomar som cancer och hjärt- och kärlförändringar tar oftast lång tid att utveckla och kan ibland inte upptäckas via blodprov. Vår avancerade MR-teknik är tillförlitlig, ofarlig och smärtfri, du utsätts inte för farlig joniserande strålning. Alla bilder granskas av erfarna specialistläkare inom radiologi. ' },
    {id: 7, name: 'Bröstrygg', price: '3 900kr', title:'Magnetröntgen Bröstrygg', detail: 'Ryggvärk är ett väldigt vanligt symtom som är den tredje vanligaste diagnosen vid långa sjukskrivningar. Långvarig ryggsmärta kan leda till stora begränsningar i vardagen och ett stort psykiskt lidande. Undersökning med magnetkamera möjliggör snabb diagnos av eventuella diskbråck och ryggmärgssjukdomar. Tillsammans med din symtombild möjliggör det en korrekt diagnos vilket ger optimala förutsättningar för rätt behandling och rehabilitering. Undersökningen är ofarlig, smärtfri och du utsätts inte för farlig joniserande strålning. Alla bilder granskas av erfarna specialistläkare inom radiologi. ' },
    {id: 8, name: 'Fot', price: '3 900kr', title:'Magnetröntgen Fot', detail: 'Smärta från foten kan bl.a. bero på inflammation, en stukning, fraktur eller hälsporre. En MR fot kartlägger fotens ben, muskler, senor och nerver och är den bästa undersökningen för att hitta en orsak till dina besvär och på så vis få rätt behandling och rehabilitering' },
    {id: 9, name: 'Fotled', price: '3 900kr', title:'Magnetröntgen Fotled', detail: 'Smärta från fotleden är ett mycket vanligt tillstånd och ofta är det kopplat till ett trauma, så som en stukning av fotleden. Detta kan leda till ledbandsskador där, i lindriga fall, ett ledband töjs ut men det kan även leda till att ett ledband helt går av. I värsta fall kan det orsaka fraktur på benet. En undersökning med MR av fotleden är den bästa undersökningen för att tidigt upptäcka ledbandsskada och på så vis få rätt behandling och rehabilitering.' }, 
    {id: 10, name: 'Hand', price: '3 900kr', title:'Magnetröntgen Hand', detail: 'En magnetröntgen av din hand kan tidigt upptäcka skador på skelett, ledband, senor och nerver som kan vara svåra att upptäcka. En tidig upptäckt gör att du snabbt kan få rätt behandling och rehabilitering.' },
    {id: 11, name: 'Hälsena', price: '3 900kr', title:'Magnetröntgen Hälsena', detail: 'En skadad hälsena kan vara smärtsam och begränsande, men det finns flera behandlingsalternativ som kan hjälpa till att lindra symptomen och främja läkningen. För att kunna behandla en skadad hälsena på rätt sätt är det viktigt att förstå vad en hälseneskada är och vad som kan orsaka den. Det är också viktigt att känna till de vanliga symptomen och när det är dags att söka medicinsk hjälp. Diagnostisering av en skadad hälsena kan göras genom läkarbesök och olika medicinska tester. När diagnosen är fastställd kan olika behandlingsalternativ användas, antingen konservativ behandling hemma eller professionell medicinsk behandling. Efter behandlingen är rehabilitering och återhämtning viktig för att återfå full funktion i hälsenan och förhindra framtida skador. I denna artikel kommer vi att gå igenom samtliga steg för att behandla en skadad hälsena och ge dig råd om hur du kan undvika framtida skador.' },
    {id: 12, name: 'Armbåge', price: '3 900kr', title:'Magnetröntgen Armbåge', detail: 'Magnetröntgen av armbågen används för att noggrant diagnostisera skador och sjukdomar i armbågsleden. Den ger detaljerade bilder av både mjukdelar och ben, vilket är särskilt användbart för att upptäcka senskador, ligamentskador, broskskador och muskelbristningar. MRT är också bra för att utvärdera artrit, inflammationer och degenerativa förändringar, samt för att upptäcka tumörer eller infektioner. Eftersom MRT inte använder röntgenstrålar är det en säker undersökningsmetod, särskilt vid behov av upprepade undersökningar.' },
    {id: 13, name: 'Underben', price: '3 900kr', title:'Magnetröntgen Underben', detail: 'Magnetröntgen av underbenet, eller MRT, används för att diagnostisera skador och sjukdomar i benets mjukdelar och skelett. Den ger detaljerade bilder av muskler, senor, ledband och ben, vilket gör den effektiv för att upptäcka muskelbristningar, senskador, benfrakturer och stressfrakturer. MRT kan också identifiera inflammationer, infektioner, och tumörer, samt utvärdera tillstånd som påverkar blodkärl och nervbanor. Eftersom MRT inte använder röntgenstrålar är det en säker metod, även för upprepade undersökningar.'  },
    {id: 14, name: 'Sacrum/Sacroliacaleder', price: '3 900kr', title:'Magnetröntgen Sacrum/Sacroliacalender', detail: 'Magnetröntgen av sacrum och sakroiliakalederna (MRT) används för att diagnostisera smärtor och problem i nedre delen av ryggen och bäckenet. MRT ger detaljerade bilder av både skelett och mjukvävnader, vilket gör det möjligt att upptäcka inflammationer, ledskador, slitage, och sakroiliit (inflammation i sakroiliakalederna). Det är särskilt användbart vid misstanke om artrit, diskproblem eller nervinklämningar. MRT är också bra för att upptäcka tumörer, infektioner eller frakturer i området. Eftersom MRT inte använder röntgenstrålar är den skonsam och säker för patienten, även vid upprepade undersökningar.' },
    {id: 15, name: 'Buk', price: '6 500kr', title:'Magnetröntgen Buk', detail: 'MR Buk undersöker lever, gallblåsa, mjälte, bukspottkörtel, njurar, lymfkörtlar och eventuell vätska i buken. Med MR erhålls detaljrika tvärsnittsbilder av bukorganen och dess olika strukturer. Detta gör att man kan detektera exempelvis tumörer eller andra tecken på cancer. Undersökningen är ofarlig, smärtfri och du utsätts inte för farlig joniserande strålning. Alla bilder granskas av erfarna specialistläkare inom radiologi.' },
    {id: 17, name: 'Hals/larynx', price: '5 800kr', title:'Magnetröntgen Hals/larynx', detail: 'Heshet och klumpkänsla i halsen är vanliga symtom från hals och svalg. MR hals och larynx avbildar halsen och struphuvudet. Struphuvudet är uppbyggt av brosk, skelett, muskler, blodkärl, nerver och stämband. Vid en MR-undersökning kartläggs dessa detaljerat och man kan upptäcka sjukliga förändringar såsom tumörer, metastaser och cystor. Man kan även upptäcka tecken till sjukdom på tunga och tonsiller (halsmandlar). Undersökningen är ofarlig, smärtfri och du utsätts inte för farlig joniserande strålning. Alla bilder granskas av erfarna specialistläkare inom radiologi. ' },
    {id: 18, name: 'Helrygg', price: '9 000kr', title:'Magnetröntgen Helrygg', detail: 'Ryggvärk är ett väldigt vanligt symtom och är den tredje vanligaste diagnosen vid långa sjukskrivningar. Långvarig ryggsmärta kan leda till stora begränsningar i vardagen och ett stort psykiskt lidande. Undersökning med magnetkamera möjliggör snabb diagnos av eventuella diskbråck och ryggmärgssjukdomar. Tillsammans med din symtombild möjliggör det en korrekt diagnos vilket ger optimala förutsättningar för rätt behandling och rehabilitering. Undersökningen är ofarlig, smärtfri och du utsätts inte för farlig joniserande strålning. Alla bilder granskas av erfarna specialistläkare inom radiologi. ' },
    {id: 19, name: 'Hjärna', price: '4 200kr', title:'Magnetröntgen Hjärna', detail: 'En magnetkameraundersökning av hjärnan kartlägger hjärnan detaljerat och kan vid ett tidigt stadium detektera sjukdomar som tumörer, stroke och tecken på demens. Den senaste MR-tekniken möjliggör en detaljerad bild av hjärnan vilket gör det lättare att se exempelvis tumörer. Ju tidigare man hittar sjukliga förändringar desto större möjlighet finns för vården att påbörja rätt behandling i tid. Undersökningen är ofarlig, smärtfri och du utsätts inte för farlig joniserande strålning. Alla bilder granskas av erfarna specialistläkare inom radiologi. ' },
    {id: 20, name: 'Käkled', price: '4 800kr', title:'Magnetröntgen Käkled', detail: 'En magnetröntgen käkled visar käkledens uppbyggnad och omkringliggande mjukdelar. Du kan upptäcka till exempel tecken till artros, inflammation eller andra ledförändringar.' },
    {id: 21, name: 'Orbita', price: '4 800kr', title:'Magnetröntgen Orbita', detail: 'MR Orbita kartlägger ögonhålan innehållande ögonmuskler, nerver och tårkanaler. Magnetkameraundersökningen är en teknik där man använder magnetfält och radiovågor för att framställa detaljerade bilder utan att använda röntgenstrålar, undersökningen är smärtfri och ofarlig. Alla bilder granskas av erfarna specialistläkare inom radiologi.'  },
    {id: 22, name: 'Prostata', price: '5 800kr', title:'Magnetröntgen Prostata', detail: 'Prostatacancer är den vanligaste cancerformen i Sverige och utgör cirka en tredjedel av alla cancerfall hos män. Tumören är vanligen mycket långsamt växande i tidigt skede. Så länge cancern är begränsad till prostatakörteln ger den sällan några symtom. Lokalt avancerad cancer och metastaserad cancer är oftast symtomgivande, men behöver inte vara det.  Vid en magnetkameraundersökning av prostatan kartlägger man förändringar i prostatan. Skulle misstänkta sjukliga förändringar föreligga kan man sedan ta exakta vävnadsprover för att utreda dessa. Välgjorda forskningsstudier visar att MR före eventuella vävnadsprover är bättre för patienten och sparar resurser för sjukvården. MR tillsammans med PSA är en tillförlitlig metod för att upptäcka och kartlägga prostatacancer. Vid upptäckt av misstänkta förändringar skickar vi remiss till urolog för vidare utredning. Undersökningen är ofarlig, smärtfri och du utsätts inte för farlig joniserande strålning. Alla bilder granskas av erfarna specialistläkare inom radiologi.' },
    {id: 24, name: 'Överarm', price: '3 900kr', title:'Magnetröntgen Överarm', detail: 'Smärta från överarm är en vanlig åkomma och kan orsaka stora inskränkningar i din vardag. Har du ont i överarm kan det bero på inflammation, artros eller skada på senor och muskler i rotatorkuffen.  En magnetkameraundersökning av överarm kan bidra med en snabb diagnos och möjlighet till rätt behandling och rehabilitering.' },
    {id: 25, name: 'Underarm', price: '3 900kr', title:'Magnetröntgen Underarm', detail: 'En undersökning med magnetkamera av underarmen kan påvisa skador eller sjukliga förändringar i skelettet eller mjukvävnaden i underarmen. Undersökningen kan även visa om nervbanorna är klämda, som vid karpaltunnelsyndrom, och om det finns pågående inflammatoriska processer i leder, kring muskler eller ligamentfästen. Handen och handleden är ytterst komplexa konstruktioner med några av kroppens mest komplicerade ledsystem. MR är en bra undersökningsmetod för att upptäcka och särskilja frakturer, artrit, skador på ligament och leder i händer och handleder.' },
    {id: 26, name: 'Handled', price: '3 900kr', title:'Magnetröntgen Handled', detail: 'Handleden är en väldigt komplex struktur av olika ben och leder som kan vinklas och röras i olika ställningar samtidigt som den klarar av att överföra stor kraft. Handleden kan drabbas av skador, inte minst från fallolyckor, samt drabbas av sjukdomar i leder och ligament som förstör motoriken. Skador och anomalier i handleden kan vara svåra att upptäcka samt besvärliga att särskilja då de ofta har likartade symptom. MR är en bra undersökningsmetod för att upptäcka och särskilja frakturer, artrit eller skador på ligament och leder. När du gör en MR av handleden är det viktigt att se till så att handen ligger mitt i tunneln vid själva bildtagningen. ' },
  ];
  const service = services.find(s => s.name === serviceName);

  return (
    <div className='main-info-service'>
    <div className="container-pricelist">
      
      <div className="main-content-info"> 
       <div className="text-content">
        <div className='title-container'>
          <h2 className='title-service'> {service.title}</h2>
        </div>
            <div>
                <h4>Varför magnetröntgen av {service.name}?</h4>
                <p>{service.detail}</p>
                <h4>Förberedelser</h4>
                <p>Du kan inte undersökas i magnetkamera om du har metallsplitter i någon del av kroppen, pacemaker, insulinpump eller annan elektronisk utrustning inopererad. Däremot går det att genomföra undersökningen om du har icke magnetisk metall, som till exempel höft- eller knäledsprotes eller tandfyllning.</p>
                <h4>Uppföljning</h4>
                <p>Efter att du har genomgått din undersökning granskas dina röntgenbilder av en röntgenspecialist. Därefter går vår läkare igenom resultatet med dig via telefon och vid behov remitteras du vidare. Du får också ditt resultat skriftligt.</p>
            </div>
        </div>
        <div >
            <DynamicForm/>
        </div>
      
      </div>
 
      </div>
    </div>
   
  );
};

export default ServiceInfo;
